project: ECBOT
game_server_port: 5003
viz_server_port: 6000
env_name: spsa_v2
render_mode: null
past_reward_threshold: -100000000
reward_backup_len: 100
gamma: 0.9997
max_train_steps: 200
num_episodes: 5000
log_every_episodes: 10
reward_fn: coins_on_platform
step_penalty: -0.5
on_bad_floor_penalty: -100.0
less_coin_penalty_multiplier: 1
on_good_floor_reward: 0
more_coin_reward_multiplier: 8
initial_position_reward: 0
good_floors:
- 4
- 5
bad_floors:
- 1
position_reward_decay_factor: 0.0
n_eval_episodes: 10
max_eval_steps: 200
eval_every_episodes: 200
seed: 1
agent_name: ppo
actor_learning_rate: 0.0001
critic_learning_rate: 0.001
decay: 0.97
ppo_clip_val: 0.2
target_kl_divergence: 0.03
max_actor_train_iterations: 5
critic_train_iterations: 10
actor_approximator: mlp
actor_num_hidden_layers: 4
actor_hidden_dim: 64
critic_approximator: mlp
critic_num_hidden_layers: 4
critic_hidden_dim: 64