defaults:
  - spsa
  - _self_

# agent
agent_name: dqn
policy_net: mlp
learning_rate: 1e-4
num_hidden_layers: 3
hidden_dim: 64
batch_size: 32
tau: 0.9996
gamma: 0.99
eps_start: 0.9
eps_end: 0.05
eps_decay: 100000
buffer_size: 10000
num_episodes: 100
max_train_steps: 50

# evaluation
n_eval_episodes: 20
max_eval_steps: 50
eval_every_episodes: 100