defaults:
  - spsa
  - _self_

# agent
agent_name: dqn
policy_net: mlp
learning_rate: 1e-4
num_hidden_layers: 1
hidden_dim: 32
batch_size: 8
tau: 0.9996
gamma: 0.99
eps_start: 0.9
eps_end: 0.05
eps_decay: 1000
buffer_size: 1000
num_episodes: 2


# evaluation
render: True
pretrained_dir: 