defaults:
  - spsa
  - _self_

# agent
agent_name: dqn
policy_net: mlp
learning_rate: 1e-4
num_hidden_layers: 3
hidden_dim: 64
batch_size: 32
tau: 0.9996
gamma: 0.99
eps_start: 0.9
eps_end: 0.05
eps_decay: 1000
buffer_size: 10000
num_episodes: 100


# evaluation
render: True
n_eval_episodes: 10
pretrained_dir: outputs/2023-06-21/18-01-21/spsa_dqn_7ZEZW/